try:
  x=10
  print(x)
except:
  print("An exception occurred")
